name: messenger_vue Deploy

on:
  push:
    branches: [ "master" ] 
    tags:
      - v.*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
          persist-credentials: false
    
    - name: Install Node (v21.1.0 - tested locally; not sure about > 21.1.0 supportion)
      uses: actions/setup-node@v4.1.0
      with:
          node-version: 21.1.0
      
    - name: Install 
      run: npm install
      
    - name: Build 
      run: npm run build
      env:
          NODE_ENV: production

    - name: Add private ssh key
      run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_SECRET_KEY_2025 }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
    - name: Connect to remote server and switch dist directory
      run: rsync -r ./dist root@164.92.95.190:/root/messenger_vue --delete 
