name: Skills_re_mind Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Add private ssh key
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_SECRET_KEY }}" > ~/.ssh/id_rsa
    - name: Execute `npm install && npm run build` on remote host
      run: ssh -o StrictHostKeyChecking=no root@142.93.112.104 'export PATH="/root/.nvm/versions/node/v16.20.2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin" && cd code/messenger_vue && git pull && npm install && npm run build'
